version: 0.2

env:
  variables:
    SOLUTION: .\CSharpHelloWorld.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.8

phases:
  build:
    commands:
      - '& nuget restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& msbuild /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK $env:SOLUTION'
artifacts:
  files:
    - .\CSharpHelloWorld\bin\Debug\*